module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'contracts',
        'sdk',
        'bundler',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'accounts',
        'paymaster',
        'nft',
        'tipping',
        'automation',
        'abstract',
        'bundler',
        'contracts',
        'sdk',
        'examples',
        'docs',
        'ci',
        'deps',
      ],
    ],
  },
};