[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# Compiler settings
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false

# EVM version
evm_version = "paris"

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction/=lib/account-abstraction/",
    "@layerzero/=lib/LayerZero/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]

# Test settings
verbosity = 2
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Coverage
coverage_exclude = ["test/**/*", "script/**/*"]

[profile.ci]
fuzz_runs = 10000

[profile.lite]
optimizer_runs = 1
fuzz_runs = 100

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"